name: tabnews_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: any
  equatable: any
  dio: any
  flutter_bloc: any
  flutter_modular: any
  flutter_screenutil: any
  flutter_markdown: any
  url_launcher: ^6.1.7
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: any
  modular_test: any

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic