name: tabnews_app
description: Conteúdo para quem trabalha com Programação e Tecncologia, mais que um app, uma ferramenta!

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.6.0
  flutter_markdown: ^0.6.13
  url_launcher: ^6.1.7
  lazy_load_scrollview: ^1.3.0
  hawk_fab_menu: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/TabNewsIcon.png
    - lib/assets/images/icon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
